version: '3.8'
services:
    web:
        container_name: flask-redis
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - redis
        volumes:
            - ./app:/src/app
        ports:
            - 8000:80
    redis:
        container_name: redis-server
        image: redis
        restart: always
        ports:
            - "6379:6379"
            